### ISSUE TITLE
Caching middleware

### ISSUE THREAD

**Issue by ksysoev** [ksysoev/wasabi#37]
It could be common feature request to cache read queries for many apis.
we should design and implement middleware that will be caching responses from BE and sending them back to the client

**Comment by shan-96** [comment]
So are you saying the this will be a server side cache?

**Comment by ksysoev** [comment]
@shan-96 yes the idea to have some thing similar to rate limiter middleware, https://github.com/ksysoev/wasabi/blob/main/middleware/request/ratelimiter.go#L17 For now we can keep implementations simple and use some in memory cache. for handling concurrent request to the same key we can use https://pkg.go.dev/golang.org/x/sync/singleflight

**Comment by ksysoev** [comment]
also for catching api response we can use connection wrapper https://github.com/ksysoev/wasabi/blob/main/channel/connection_wrapper.go

**Comment by shan-96** [comment]
I'm adding some proposals here. Let me know if a document with details are need.

1. Caching lib prospects

- https://github.com/VictoriaMetrics/fastcache - thread safe + in memory, might be suitable for large number of entries and small GC overhead
- https://github.com/dgraph-io/ristretto - probably same as above but more popular and there might be option to offload the cache to separate layer or outside main memory
- https://github.com/akyoto/cach - very simple, does one job
- https://github.com/OrlovEvgeny/go-mcache - pointer based in memory cache

![image](https://github.com/ksysoev/wasabi/assets/16632302/87230b80-a391-4547-a820-520d09fcc8fe)

![image](https://github.com/ksysoev/wasabi/assets/16632302/bd2c7e32-dd93-4ed5-9ada-e87bd8566c62)

![image](https://github.com/ksysoev/wasabi/assets/16632302/caebe971-6ce8-40d2-80b6-82d2e494c517)


I personally favor ristretto just because it is a stable project and caching middleware is an important north star for wasabi so we should think long term.

Comments?

**Comment by ksysoev** [comment]
@shan-96 ristretto looks good, we can start with it, as a next steps we can provide option to provide customer cache storage that satisfy the interface.

**Comment by ksysoev** [comment]
@shan-96 do you have any concern if i takeover this issue?

**Comment by shan-96** [comment]
@ksysoev go ahead

**Comment by ksysoev** [comment]
Implemented in #97, I decided to go with https://github.com/jellydator/ttlcache as it looks way simpler and looks enough for current needs.

**Comment by shan-96** [comment]
ah yes `ttlcache` is a good alternative
